<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_alamteguhgmail.com</name>
   <tag></tag>
   <elementGuidId>040884a9-f615-4290-83ee-3a4ae2545654</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../report/LoImmsummaryRocDetailsByEmail_Md?email=alamteguh@gmail.com&amp;startingDate=2018-09-01&amp;endDate=2018-09-30&amp;pStart=&amp;pEnd=&amp;lOfficer=1941</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>alamteguh@gmail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTableInf&quot;)/tbody[2]/tr[1]/td[7]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
