<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AMW6117YAHOO.COM</name>
   <tag></tag>
   <elementGuidId>9397e45d-6792-4871-8554-4e9144d0219b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../report/LoImmsummaryRocDetailsByEmail_Fw.action?email=AMW6117@YAHOO.COM&amp;startingDate=2018-08-01&amp;endDate=2018-08-30&amp;pStart=&amp;pEnd=&amp;lOfficer=2004</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMW6117@YAHOO.COM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTableInf&quot;)/tbody[2]/tr[1]/td[7]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
