<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select TM Name -    A</name>
   <tag></tag>
   <elementGuidId>5534974d-ccef-4fc9-83be-1404dca05dbb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filterTmname</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterTmname</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
     - Select TM Name -
    ALL
    MYEG
    MYEGSE007371
    MYEGZULKIFLY
    MYEGBU003372
    MYEGAZLINA79
    MYEGSG003371
    MYEGKB012371
    MYEGIP004371
    MYEGSI004374
    MYEGME008371
    MYEGTI004373
    MYEGTA004372
    MYEGJB812000
    MYEGTM2009
    MYEGAIZAACC
    MYEGPROJECT1
    MYEGFARAHRTX
    MYEGPHOEBEACC
    MYEGSURATATX
    MYEGNADIARTX
    MYEGIRARTXCC
    MYEGLINARTX
    MYEGCRRTX919
    MYEGCRRTX273
    MYEGCRRTX631
    MYEGEYLACRTX
    MYEGHUSNARTX
    MYEGSHAHRRTX
    MYEGCRRTX103
    MYEGRTXPP
    MYEGAZURACC
    MYEGLIZARTX
    MYEGTEST
    MYEGGANESH


</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterTmname&quot;)</value>
   </webElementProperties>
</WebElementEntity>
